//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagdievaStudyPR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int ID { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> YearOfAwardingTheTitle { get; set; }
    }
}
