//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagdievaStudyPR.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SagdievaStudyPREntities : DbContext
    {
        public SagdievaStudyPREntities()
            : base("name=SagdievaStudyPREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Animals_Sagdieva> Animals_Sagdieva { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Chair> Chair { get; set; }
        public virtual DbSet<ChairBoss> ChairBoss { get; set; }
        public virtual DbSet<Control_Sagdieva> Control_Sagdieva { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Country_Sagdieva> Country_Sagdieva { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flowers_Sagdieva> Flowers_Sagdieva { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentPR10> StudentPR10 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<GymnasiumPupil> GymnasiumPupil { get; set; }
    }
}
